development:
  adapter: postgresql
  encoding: unicode
  database: RailsTest_development
  pool: 5
  timeout: 5000
  username: algoemtrix
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RailsTest_test
  pool: 5
  timeout: 5000
  username: algoemtrix
  password:
