development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  timeout: 5000
  username: algoemtrix
  password: satyam

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  timeout: 5000
  username: algoemtrix
  password: satyam
